spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/portfolio_tracker"
      driver-class-name: org.postgresql.Driver
      username: jinto
      password: password
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

